application: dotty-dots
version: 4
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

# Contains CSS/JS and alphabet.js    
- url: /static
  static_dir: static

# Dynamically generated alphabet.js file from
# latest db data.
- url: /secret-character-editor/alphabet.js
  script: edit.py
  login: admin
  
- url: /secret-character-editor/static
  static_dir: secret-character-editor/static
  login: admin
  
- url: /secret-character-editor/.*
  script: edit.py
  login: admin

# For testing e.g. 
# /testarea/shapes.html
# /testarea/fades.html  
- url: /testarea
  static_dir: testarea
  login: admin
    
# For import/export.
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /.*
  static_files: index.html
  upload: index.html
